### ISSUE TITLE
Loading a map in deathmatch mode in reaprb81.zip segfaults

### ISSUE THREAD

**Issue by SpiritQuaddicted** [SpiritQuaddicted/reQuiem#8]
reaperbots reaprb81.zip segfaults. Try either "-game rpbot +map dm1" or in-game "deathmatch 1" then "map dm1". Starting a sp game works. I am on Linux.

**Comment by neogeographica** [comment]
This happens with any listen server game using reQuiem, not just reaperbots.

 Some context:
- Con_Print (and therefore Con_Printf too) calls SCR_UpdateScreen.
- SCR_UpdateScreen calls Sbar_Draw -> Sbar_DrawScoreboard -> Sbar_DeathmatchOverlay -> Sbar_SortFrags.
- Sbar_SortFrags requirs cl.scores to have been allocated and initialized.

Now, where we get into trouble:
- CL_ParseServerInfo can do some Con_Print and Con_Printf calls.
- If cl_demoseek is false, it's definitely going to do a Con_Print BEFORE it allocates cl.scores.
- Therefore we get a NULL pointer deref in Sbar_SortFrags.

Probably this can be solved be re-ordering some things in CL_ParseServerInfo, but there's a few landmines in there with all the new demoseek stuff and support for different protocols... don't want to break something else when moving the cl.scores allocation.

**Comment by neogeographica** [comment]
Maybe the right solution -- speaking as a guy who REALLY isn't familiar yet with Quake-engine internals -- is to skip some or all of the statusbar-fiddling during SCR_UpdateScreen if cls.signon != SIGNONS (and/or some of the other "map not running yet" criteria from the callsite in Con_Print).

**Comment by neogeographica** [comment]
Here's a change I tried out. Adding this block:

``` c
    // Abort if not fully signed on yet.
    if (cls.signon != SIGNONS)
        return;
```

to the beginning of both Sbar_DeathmatchOverlay and Sbar_MiniDeathmatchOverlay. This allowed me to start a listen server correctly. I could also start a game with frikbots, add multiple bots, and play through multiple maps. The scoreboard worked as expected. (I haven't re-tried reaperbots specifically yet.)

I'm not yet saying this is the best way to fix the underlying issue. It might just be a bandaid on something fragile that should be better fixed in a different place.

I'll continue to play around with it.

**Comment by neogeographica** [comment]
As far as I can tell this is fixed by https://github.com/SpiritQuaddicted/reQuiem/pull/26 so closing the issue.
